create table if not exists public.demos (
id bigint generated by default as identity primary key, demo_code text unique not null,
farmer_name text not null, mobile text, district text not null, upazila text not null,
union_name text, village text, crop text, variety text, sowing_date date,
area_decimal double precision, latitude double precision, longitude double precision,
gps_accuracy double precision, photo_path text, created_at timestamptz default now());

create table if not exists public.field_data (
id bigint generated by default as identity primary key, demo_code text not null,
entry_date date, fertilizer text, irrigation text, crop_condition text,
pest_disease text, farmer_feedback text, latitude double precision,
longitude double precision, gps_accuracy double precision, photo_path text,
created_at timestamptz default now());

create table if not exists public.harvest (
id bigint generated by default as identity primary key, demo_code text,
harvest_date date, grain_kg double precision, area_decimal double precision,
yield_t_ha double precision, remarks text);

alter table public.demos enable row level security;
alter table public.field_data enable row level security;
alter table public.harvest enable row level security;

create policy "anon demos select" on public.demos for select to anon using (true);
create policy "anon demos insert" on public.demos for insert to anon with check (true);
create policy "anon field select" on public.field_data for select to anon using (true);
create policy "anon field insert" on public.field_data for insert to anon with check (true);
create policy "anon harvest select" on public.harvest for select to anon using (true);

insert into storage.buckets (id,name,public) values ('field-photos','field-photos',true)
on conflict (id) do nothing;
create policy "public photo upload" on storage.objects for insert to anon
with check (bucket_id='field-photos');
create policy "public photo read" on storage.objects for select to anon
using (bucket_id='field-photos');
